"""Add user_id relation

Revision ID: 0f3defdee040
Revises: 595bde972f7b
Create Date: 2026-02-25 15:20:52.330925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3defdee040'
down_revision: Union[str, Sequence[str], None] = '595bde972f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoros', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pomodoros_habit_id_fkey'), 'pomodoros', type_='foreignkey')
    op.create_foreign_key(None, 'pomodoros', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pomodoros', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pomodoros', type_='foreignkey')
    op.drop_constraint(None, 'pomodoros', type_='foreignkey')
    op.create_foreign_key(op.f('pomodoros_habit_id_fkey'), 'pomodoros', 'habits', ['habit_id'], ['id'])
    op.drop_column('pomodoros', 'user_id')
    # ### end Alembic commands ###
