"""Add color field

Revision ID: 1a1bd51d4506
Revises: d593ba205ed8
Create Date: 2026-02-26 12:05:18.711890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1bd51d4506'
down_revision: Union[str, Sequence[str], None] = 'd593ba205ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('color', sa.String(length=125), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'color')
    # ### end Alembic commands ###
