"""Add log date

Revision ID: 595bde972f7b
Revises: 205aa654bb9b
Create Date: 2026-02-25 14:20:38.632668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595bde972f7b'
down_revision: Union[str, Sequence[str], None] = '205aa654bb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('log_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_logs', 'log_date')
    # ### end Alembic commands ###
