"""Add new columns

Revision ID: ad62bf68133a
Revises: 1a1bd51d4506
Create Date: 2026-02-26 16:16:17.811037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad62bf68133a'
down_revision: Union[str, Sequence[str], None] = '1a1bd51d4506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_completions_id'), 'habit_completions', ['id'], unique=False)
    op.add_column('habits', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('best_streak', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('last_completed_date', sa.Date(), nullable=True))
    op.drop_column('habits', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('status', sa.VARCHAR(length=100), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('habits', 'last_completed_date')
    op.drop_column('habits', 'best_streak')
    op.drop_column('habits', 'current_streak')
    op.drop_index(op.f('ix_habit_completions_id'), table_name='habit_completions')
    op.drop_table('habit_completions')
    # ### end Alembic commands ###
