"""Update tables

Revision ID: d593ba205ed8
Revises: 0f3defdee040
Create Date: 2026-02-26 10:25:07.407519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd593ba205ed8'
down_revision: Union[str, Sequence[str], None] = '0f3defdee040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('days_to_log', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('habits', sa.Column('status', sa.String(length=100), server_default=sa.text('false'), nullable=False))
    op.add_column('habits', sa.Column('logs_to_complete', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('habits', 'logs_to_complete')
    op.drop_column('habits', 'status')
    op.drop_column('habits', 'days_to_log')
    # ### end Alembic commands ###
